ICI : T_id est le pas (temps)

Les actions sont : 'rating', 'food_rating' et 'service_rating'

Vous pouvez utiliser le format que vous préférez : 
- DataFrame de pandas (df_data) 
- un tableau numpy (np_data), alors vous allez faire : my_data = np_data
- un dictionnaire (in_data), vous allez faire : my_data = in_data

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# DataFrame
df_data_initial = pd.read_csv("rating_final_user.csv")
df_data = df_data.loc[:, ["T_ID", "rating", "food_rating", "service_rating"]]

# Dictionnaire
in_data = df_data_initial.to_dict()

# Tableau numpy
np_data = df_data_initial.loc[:, ["T_ID", "rating", "food_rating", "service_rating"]].to_numpy()

In [10]:
# 
df_data.head(5)

T_ID  rating  food_rating  service_rating
0     1       1            1               2
1     2       1            1               1
2     3       1            1               1
3     4       1            1               1
4     5       1            1               1

In [11]:
print(np_data)

[[   1    1    1    2]
 [   2    1    1    1]
 [   3    1    1    1]
 ...
 [1159    2    2    2]
 [1160    2    2    1]
 [1161    1    2    1]]


In [12]:
print(in_data)

{'T_ID': {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 35, 35: 36, 36: 37, 37: 38, 38: 39, 39: 40, 40: 41, 41: 42, 42: 43, 43: 44, 44: 45, 45: 46, 46: 47, 47: 48, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 57, 57: 58, 58: 59, 59: 60, 60: 61, 61: 62, 62: 63, 63: 64, 64: 65, 65: 66, 66: 67, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75, 75: 76, 76: 77, 77: 78, 78: 79, 79: 80, 80: 81, 81: 82, 82: 83, 83: 84, 84: 85, 85: 86, 86: 87, 87: 88, 88: 89, 89: 90, 90: 91, 91: 92, 92: 93, 93: 94, 94: 95, 95: 96, 96: 97, 97: 98, 98: 99, 99: 100, 100: 101, 101: 102, 102: 103, 103: 104, 104: 105, 105: 106, 106: 107, 107: 108, 108: 109, 109: 110, 110: 111, 111: 112, 112: 113, 113: 114, 114: 115, 115: 116, 116: 117, 117: 118, 118: 119, 119: 120, 120: 121

<h3>Faire UCB avec initialisation à zéro. </h3>

In [ ]:


# A changer si on veut utiliser un autre format 
??? 
my_data = np_data
c = 3 # essayer avec plusieurs valeur de c = 2, 5, 10
out_reward = {"rating":[], "food_rating":[], "service_rating":[]}

# On stocke ici les Qta = valeurs estimes pour chaque action, à un moment T donné
Qta = {"rating":0, "food_rating":0, "service_rating":0}
#Qta = {"rating":3, "food_rating":3, "service_rating":3}


out_UCB_reward = {"rating":[], "food_rating":[], "service_rating":[]}

# pour chaque pas :
for i in range(my_data.shape[0]):
    
    #pour chaque action:
    for action in Qta.keys():
        
        #on recupere la recompense correspondante 
        reward = ???

        # On calcule Qt(a) pour cette action, selon la règle de la mise à jour incrémentale
        QTA = ???

        # Ensuite on la met dans Qta

        # On rajoute la recompense à la liste des recompenses correspondante dans out_reward :
        ???

        # On calcule, pour chaque action de out_reward, le UCB, selon la formule du cours 1
        # On le rajoute en out_UCB_reward
        ???
    
    
# On affiche out_UCB_reward avec matplotlib
x = range(out_UCB_reward["A1"]).tolist()

# pour chaque clé k dans out_UCB_reward
for k in out_UCB_reward.keys()
    yk =  ??? # on recupere la liste
    plt.plot(x,yk)
plt.show()    
    
    



<h3>Faire UCB avec initialisation à 5. </h3>

In [ ]:
# A changer si on veut utiliser un autre format 
??? 
my_data = np_data
c = 3 # essayer avec plusieurs valeur de c = 2, 5, 10
out_reward = {"rating":[], "food_rating":[], "service_rating":[]}

# On stocke ici les Qta = valeurs estimes pour chaque action, à un moment T donné
Qta = {"rating":5, "food_rating":5, "service_rating":5}
#Qta = {"rating":3, "food_rating":3, "service_rating":3}


out_UCB_reward = {"rating":[], "food_rating":[], "service_rating":[]}

# pour chaque pas :
for i in range(my_data.shape[0]):
    
    #pour chaque action:
    for action in Qta.keys():
        
        #on recupere la recompense correspondante 
        reward = ???

    
        # On calcule Qt(a) pour cette action, selon la règle de la mise à jour incrémentale
        QTA = ???

        # Ensuite on la met dans Qta

        # On rajoute la recompense à la liste des recompenses correspondante dans out_reward :
        ???

        # On calcule, pour chaque action de out_reward, le UCB, selon la formule du cours 1
        # On le rajoute en out_UCB_reward
        ???


# On affiche out_UCB_reward avec matplotlib
x = range(out_UCB_reward["A1"]).tolist()

# pour chaque clé k dans out_UCB_reward
for k in out_UCB_reward.keys()
    yk =  ??? # on recupere la liste
    plt.plot(x,yk)
plt.show()    